### ISSUE TITLE
Could not create vue project in node v12.18.1

### ISSUE THREAD

**Issue by fengxinming** [vuejs/create-vue#105]
```bash
/Users/jesse/.tnpm/_tnpx/7033/lib/node_modules/create-vue/outfile.cjs:5681
  const isFeatureFlagsUsed = typeof (argv.default ?? argv.ts ?? argv.jsx ?? argv.router ?? argv.pinia ?? argv.tests ?? argv.vitest ?? argv.cypress ?? argv.eslint) === "boolean";
                                                   ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by LinusBorg** [comment]
Required base version is Node 14. 

Node 12 has already reached EOL, it's not even getting security updates as of  April 30th 2022.

So we don't support it anymore.
