### ISSUE TITLE
How to run cypress on newly scaffolded project?

### ISSUE THREAD

**Issue by jrefior** [vuejs/create-vue#197]
On November 15, I ran `npm init vue@latest` to start a new project with the following options:

- Typescript: yes
- JSX: no
- Vue router: no
- Pinia: yes
- Vitest: yes
- End-to-end: cypress
- ESLint: yes
- Prettier: yes

Whenever I try to run the example test in cypress, cypress errors with this:

Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at makeSourceMapAndFinish (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/node_modules/ts-loader/dist/index.js:58:5)
    at successLoader (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/node_modules/ts-loader/dist/index.js:40:5)
    at Object.loader (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/node_modules/ts-loader/dist/index.js:23:5)
    at LOADER_EXECUTION (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array. (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/graceful-fs/graceful-fs.js:123:16
    at /home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:123:16
    at /home/jrefior/.cache/Cypress/10.11.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

That's running `npx cypress open` => E2E testing => Chrome => example.cy.ts .

I've tried both npm run dev and npm run build and then hosting files on a web server. It appears it does not get far enough in test execution to query the server, it fails on something more fundamental before then.

This is my cypress.config.ts, I've changed the port here depending on whether I was running via `npm run dev` or my web server after doing a build, but that hasn't made a difference, except when the port was wrong I did see a warning in the cypress ui prior to running a test.

```
import { defineConfig } from "cypress";

export default defineConfig({
  e2e: {
    specPattern: "cypress/e2e/**/*.{cy,spec}.{js,jsx,ts,tsx}",
    baseUrl: "http://localhost:4173",
  },
});
```

I noticed the error said `cypress.config.js`, but I don't have that file, I have `cypress.config.ts`. I tried looking in cypress settings in the UI and it appeared to be reading the specPattern from my `cypress.config.ts` file, so I wonder if that .js in the error is just hard-coded.

Is this a problem with using vite? I see webpack referenced in some of the paths.

**Comment by jrefior** [comment]
I'm on Fedora 36 and I thought maybe this could be related to OpenSSL (see, e.g., [StackOverflow](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported))

So I just applied every update available for Fedora 36, and then tried testing again. Cypress crashed in the same way.

**Comment by jrefior** [comment]
Today I upgraded to Fedora 37, and that installed Node.js 18.7.0. The test ran successfully on that version. Closing this issue.
