### ISSUE TITLE
Newly scaffolded project Playwright test doesn't pass

### ISSUE THREAD

**Issue by vincerubinetti** [vuejs/create-vue#259]
Setup:

```
> yarn create vite           
yarn create v1.22.19
success Installed "create-vite@4.3.1" with binaries:
      - create-vite
      - cva
✔ Project name: … create-vue
✔ Select a framework: › Vue
✔ Select a variant: › Customize with create-vue ↗
yarn create v1.22.19
success Installed "create-vue@3.6.1" with binaries:
      - create-vue
Vue.js - The Progressive JavaScript Framework

✔ Add TypeScript? … No / ✅Yes
✔ Add JSX Support? … ✅No / Yes
✔ Add Vue Router for Single Page Application development? … No / ✅Yes
✔ Add Pinia for state management? … ✅No / Yes
✔ Add Vitest for Unit Testing? … No / ✅Yes
✔ Add an End-to-End Testing Solution? › Playwright
✔ Add ESLint for code quality? … No / ✅Yes
✔ Add Prettier for code formatting? … No / ✅Yes
```

Chromium error:

```
Test timeout of 30000ms exceeded.

Error: page.goto: net::ERR_ABORTED; maybe frame was detached?
=========================== logs ===========================
navigating to "http://localhost:5173/", waiting until "load"
============================================================

  4 | // https://playwright.dev/docs/intro
  5 | test('visits the app root url', async ({ page }) => {
> 6 |   await page.goto('/');
    |              ^
  7 |   await expect(page.locator('div.greetings > h1')).toHaveText('You did it!');
  8 | })
  9 |

    at /Users/vincerubinetti/Desktop/create-vue/e2e/vue.spec.ts:6:14

Pending operations:
  - page.goto at e2e/vue.spec.ts:6:14

✅ 4.0sBefore Hooks
❌ 29.7spage.goto(/)— vue.spec.ts:6
❌ 98msAfter Hooks
```

Firefox/Webkit errors are the same, except for:

```
Error: page.goto: Navigation failed because page was closed!
```

I'm on MacOS (an M1 machine). I'm completely new to Playwright so I apologize if this issue belongs somewhere else. I can't find any info on Google for the error message. Any insights are appreciated.

---

I tried it on my Windows 10 machine and it worked. Might be a problem with the M1.

**Comment by vincerubinetti** [comment]
Apologies. It is now working. I believe restarting my laptop was the trick (something I do surprisingly little). Maybe there was a process running on a port that was messing something up, I don't know. I wish Playwright (or Vite?) gave me a more helpful error.

Another thing I should note. Before this fixed itself, I tried starting a new "Playwright project" on its own to investigate. I tried one of the boilerplate tests from that in the create-vue project:

```
test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await expect(page).toHaveTitle(/Playwright/);
});
``` 

And it worked fine. So, it was able to run everything just fine and visit a public URL. I guess in my original case it wasn't able to properly start the dev server and/or render the vue app at the right port or something like that.
