### ISSUE TITLE
Error when running npm init vue@latest

### ISSUE THREAD

**Issue by sharpdesignllc** [vuejs/create-vue#42]
npm-cache\_npx\2f7e7bff16d1c534\node_modules\create-vue\outfile.cjs:5897
const userAgent = process.env.npm_config_user_agent ?? "";
                                                                                          ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by therealshark** [comment]
This operator ([Logical nullish assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment)) is available since node v15, it seems you are using an older version of node. Updating to node 16 (lts) or 17  should fix it :)

**Comment by sharpdesignllc** [comment]
Updating node did the trick, thanks!
