### ISSUE TITLE
Quickstart project fails on "npm run dev" (Can't find `@rollup/rollup-darwin-x64`)

### ISSUE THREAD

**Issue by schwa423** [vuejs/create-vue#427]
Platform: MacOS 14.2.1
Browser: Chrome 120.0.6099.234 arm64
Node Version: 21.6.0
Npm Version: 10.2.4

I'm trying to follow the Vue.js Quick Start instructions (https://vuejs.org/guide/quick-start.html).  Steps taken:
- run `npm create vue@latest` in a new directory
- answer the interactive questions (set project name to "vue-quickstart" and answer "No" to all other questions)
- `cd vue-quickstart2`
- `npm install`... seems to succeed
- `npm run dev`

The last step fails.  Here's the output:
```
> vue-quickstart2@0.0.0 dev
> vite

/Users/josh/code/frontend-experiments/vue-quickstart2/node_modules/rollup/dist/native.js:87
		throw new Error(
		      ^

Error: Cannot find module @rollup/rollup-darwin-x64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/josh/code/frontend-experiments/vue-quickstart2/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/Users/josh/code/frontend-experiments/vue-quickstart2/node_modules/rollup/dist/native.js:96:48)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-x64'
  Require stack:
  - /Users/josh/code/frontend-experiments/vue-quickstart2/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
      at Module._load (node:internal/modules/cjs/loader:985:27)
      at Module.require (node:internal/modules/cjs/loader:1235:19)
      at require (node:internal/modules/helpers:176:18)
      at requireWithFriendlyError (/Users/josh/code/frontend-experiments/vue-quickstart2/node_modules/rollup/dist/native.js:69:10)
      at Object.<anonymous> (/Users/josh/code/frontend-experiments/vue-quickstart2/node_modules/rollup/dist/native.js:96:48)
      at Module._compile (node:internal/modules/cjs/loader:1376:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
      at Module.load (node:internal/modules/cjs/loader:1207:32)
      at Module._load (node:internal/modules/cjs/loader:1023:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/josh/code/frontend-experiments/vue-quickstart2/node_modules/rollup/dist/native.js'
    ]
  }
}

Node.js v21.2.0
```

As suggested, I tried removing `package-lock.json` and `node_modules/` then retrying `npm install; npm run dev`.  The result is the same.

**Comment by schwa423** [comment]
Perhaps there is an architecture issue?  It's looking for the `x64` version: `@rollup/rollup-darwin-x64`, but it should be looking for the `arm64` version, I think.

I'm using `node` and `npm` installed by Homebrew,  which I believe is set up for native `arm64`.  Excerpts from `brew config`:
```
HOMEBREW_VERSION: 4.2.4
...
CPU: 10-core 64-bit arm_firestorm_icestorm
...
Rosetta 2: false
```

According to https://github.com/orgs/Homebrew/discussions/3223, this proves that my Homebrew is natively using the `arm64` architecture.

I wonder if this is an upstream configuration issue with `@rollup`?  Sorry, I'm not very good at debugging this stuff, I'm mostly using C++.

**Comment by schwa423** [comment]
Nevermind I figured it out.  Somehow I had another version of node in `~/node_modules/node`; when I ran `npm run dev` it somehow munged the $PATH to use that one instead of the one I installed with Homebrew.  This other version of node was x64.

Deleting the directory `~/node_modules/node` fixed my issue.
