### ISSUE TITLE
create vue project error .   TypeError: (0 , import_node_util.parseArgs) is not a function

### ISSUE THREAD

**Issue by wordscode** [vuejs/create-vue#469]
C:\Users\czk>node --version
v18.1.0

C:\Users\czk>npm --version
8.8.0

C:\Users\czk>pnpm --version
8.15.4

C:\Users\czk>pnpm create vue
.../Local/pnpm/store/v3/tmp/dlx-32624    |   +1 +
.../Local/pnpm/store/v3/tmp/dlx-32624    | Progress: resolved 1, reused 1, downloaded 0, added 1, done

Vue.js - The Progressive JavaScript Framework

TypeError: (0 , import_node_util.parseArgs) is not a function
    at init (C:\Users\czk\AppData\Local\pnpm\store\v3\tmp\dlx-32624\node_modules\.pnpm\create-vue@3.10.1\node_modules\create-vue\outfile.cjs:4478:72)
    at Object.<anonymous> (C:\Users\czk\AppData\Local\pnpm\store\v3\tmp\dlx-32624\node_modules\.pnpm\create-vue@3.10.1\node_modules\create-vue\outfile.cjs:4858:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

![image](https://github.com/vuejs/create-vue/assets/75980075/a502fdf0-566b-446d-860e-ab400ffa4fd2)

**Comment by wordscode** [comment]
I have tried uninstalling and reinstalling pnpm and still got an error

**Comment by cexbrayat** [comment]
Hi @wordscode 

It looks like you have an old nodejs version. Try to install a more recent one (18.19 for example) and it will solve your issue

**Comment by wordscode** [comment]
> Hi  嗨 @wordscode
> 
> It looks like you have an old nodejs version. Try to install a more recent one (18.19 for example) and it will solve your issue看起来你有一个旧的nodejs版本。尝试安装一个更新的（例如18.19），它将解决您的问题

use this version could create successfully
```
pnpm create vue@3.9.2 gp-admin
```

3.10.0 , 3.10.1 report an error

**Comment by cexbrayat** [comment]
Yes, we now rely on a more up to date nodejs version to parse args since v3.10 👍

**Comment by Yordan-Ramchev** [comment]
FYI — based on Node changelog https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2022-10-13-version-18110-current-danielleadams 

[Node.js](https://nodejs.org/) version 18.11.0 or higher should be OK
